services:
  backend:
    container_name: backend-api
    build: .
    restart: unless-stopped
    links:
      - db
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: "/app/public"
      PHP_DISMOD: ioncube
    ports:
      - 8000:80

  db:
    container_name: db-mariadb
    image: mariadb:10.11.8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    ports:
      - "33306:3306"
